spring:
  data:
    mongodb:
      database: test
      host: my.tencent.cn
      username: test_user
      password: '1049832901'
      authentication-database: test
      port: 27011
      grid-fs-database: admin

  datasource:
    url: jdbc:mysql://my.tencent.cn:3306/
    password:


test:
  enable: false